#!/bin/sh

# Written by GuoJun
# Dec 3 2024

export OSLAB_PATH=$(dirname `which $0`)

if [ -e "$OSLAB_PATH/hdc-0.11.img.lock" ]; then
	rm -rf $OSLAB_PATH/hdc-0.11.img.lock
	echo delete hdc-0.11.img.lock 
fi

qemu-system-i386 -m 16M -boot a -drive file=$OSLAB_PATH/linux-0.11/Image,format=raw,if=floppy -drive file=$OSLAB_PATH/hdc-0.11.img,format=raw -s -S
