#!/bin/sh

# Written by GuoJun
# Dec 3 2024

export OSLAB_PATH=$(dirname `which $0`)

if [ -e "$OSLAB_PATH/hdc-0.11.img.lock" ]; then
	rm -rf $OSLAB_PATH/hdc-0.11.img.lock
	echo delete hdc-0.11.img.lock 
fi

sudo mount -t minix -o loop,offset=1024 $OSLAB_PATH/hdc-0.11.img $OSLAB_PATH/hdc
