#!/bin/sh

# Written by GuoJun
# Dec 3 2024

export OSLAB_PATH=$(dirname `which $0`)

if [ -e "$OSLAB_PATH/hdc-0.11.img.lock" ]; then
	rm -rf $OSLAB_PATH/hdc-0.11.img.lock
	echo delete hdc-0.11.img.lock 
fi

if [ ! -e "$OSLAB_PATH/hdc/umounted" ]; then
	echo umount hdc first
	sudo umount $OSLAB_PATH/hdc
	if [ "$?" != "0" ]; then
		exit
	fi
fi

gdb -x $OSLAB_PATH/gdb-cmd.txt $OSLAB_PATH/linux-0.11/tools/system
